name: drive_to_youtube
description: App to download videos from Google Drive and upload them to Youtube

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  googleapis: any
  googleapis_auth: any
  google_sign_in: ^5.0.0
  flutter_bloc: ^6.1.3
  equatable: ^2.0.0
  url_launcher: ^6.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/img_not_found.png
    - assets/youtube_logo.png
    - assets/dummy_data.json
